import { Injectable, OnModuleInit, OnModuleDestroy, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";

// PrismaClient is generated by `prisma generate` into node_modules/.prisma/client
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require("@prisma/client");

/**
 * PrismaService — singleton Prisma client for the BYUND API service.
 * Uses the pg adapter (Prisma 7 driver adapter pattern).
 */
@Injectable()
export class PrismaService implements OnModuleInit, OnModuleDestroy {
  private readonly logger = new Logger(PrismaService.name);
  private readonly client: InstanceType<typeof PrismaClient>;

  constructor(private readonly cfg: ConfigService) {
    const pool = new Pool({
      connectionString: cfg.getOrThrow<string>("DATABASE_URL"),
      ssl: cfg.get("NODE_ENV") === "production" ? { rejectUnauthorized: false } : false,
      max: 10,
      idleTimeoutMillis: 30_000,
    });
    this.client = new PrismaClient({ adapter: new PrismaPg(pool) });
  }

  async onModuleInit() {
    await this.client.$connect();
    this.logger.log("Connected to BYUND database");
  }

  async onModuleDestroy() {
    await this.client.$disconnect();
  }

  // Proxy all Prisma model accessors so callers can do:
  //   this.prisma.user.findUnique(...)
  //   this.prisma.$transaction(...)
  get user()             { return this.client.user; }
  get workspace()        { return this.client.workspace; }
  get workspaceMember()  { return this.client.workspaceMember; }
  get workspaceSettings(){ return this.client.workspaceSettings; }
  get auditLog()         { return this.client.auditLog; }
  get subscription()     { return this.client.subscription; }

  $transaction(...args: Parameters<typeof this.client.$transaction>) {
    return this.client.$transaction(...args);
  }
  $queryRaw(...args: Parameters<typeof this.client.$queryRaw>) {
    return this.client.$queryRaw(...args);
  }
  $executeRaw(...args: Parameters<typeof this.client.$executeRaw>) {
    return this.client.$executeRaw(...args);
  }
}
